name: Terraform

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # main.tf is at the REPO ROOT
      - name: Terraform Init
        run: terraform -chdir="." init

      - name: Terraform Plan
        run: terraform -chdir="." plan -input=false
