name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    # main.tf is at the REPO ROOT
    env:
      TF_DIR: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform -chdir="${{ env.TF_DIR }}" init

      - name: Terraform Format
        run: terraform -chdir="${{ env.TF_DIR }}" fmt -check

      - name: Terraform Plan
        run: terraform -chdir="${{ env.TF_DIR }}" plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform -chdir="${{ env.TF_DIR }}" apply -auto-approve -input=false
